# Generated by Django 3.2 on 2021-04-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='cover_pics'),
        ),
    ]
