# Generated by Django 3.2 on 2021-04-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_img',
            field=models.ImageField(default='default.png', upload_to='cover_pics'),
        ),
    ]
